services:
  db:
    platform: linux/amd64
    image: postgres:16
    env_file:
      - ./.env
    ports:
      - '5432:5432'
  validator:
    platform: linux/amd64
    image: rub21/hudhud-notes-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./:/main
    ports:
      - '8000:8000'
    depends_on:
      - db
